package com.simulator.utils;

/**
 * @author harshil.sharma
 *
 */
public class WSConstants {
	
	public enum WSExceptionConstant {
		USER_NOT_FOUND(30111),
		USER_NOT_AUTHORIZED(30112),
		USER_ALREADY_LOGIN(-50167),
		USER_ACCOUNT_LOCKED(-50208),
		USER_NOT_EXIST(-50003),
		USER_FIRST_LOGIN_CHANGE_PASSWORD(-50222),
		USER_CHANGE_PASSWORD_POLICY_ERROR(-50209),
		USER_CHANGE_NEWPASSWORD_POLICY_ERROR(-50211),
		INVALID_PASSWORD(-50127),
		TOKEN_ID_CANNOT_BE_BLANK(50004),
		USER_ID_CANNOT_BE_BLANK(50005),
		USERNAME_CANNOT_BE_BLANK(50006),
		PASSWORD_CANNOT_BE_BLANK(50007),
		USERTYPE_CANNOT_BE_BLANK(50008),
		GENERIC_ERROR(-30404),
		INVALID_SESSION(-1000),
		INVALID_REQUEST(-1001),
		INVALID_REQUEST_COOKIE_NOT_PRESENT(-1002),
		RESOURCE_DOES_NOT_EXIST(71000),
		RESOURCE_ID_CANNOT_BE_BLANK(71001),
		NO_RESOURCE_TO_SAVE(71002),
		RESOURCE_NAME_CANNOT_BE_BLANK(71003),
		SPECIFIED_RESOURCES_DO_NOT_EXIST(71004),
		NO_RESOURCE_TO_DELETE(71005),
		GROUP_DOES_NOT_EXIST(72000),
		GROUP_ID_CANNOT_BE_BLANK(72001),
		GROUP_NAME_CANNOT_BE_BLANK(72002),
		SCENARIO_NOT_FOUND(73000),
		SCENARIO_ID_CANNOT_BE_BLANK(73001),
		SCENARIO_NAME_CANNOT_BE_BLANK(73002),
		SCENARIO_NO_DATA_TO_SAVE(73003),
		SCENARIO_INVALID_HISTORICAL_START_DATE(73004),
		SCENARIO_INVALID_HISTORICAL_END_DATE(73005),
		SIMULATION_INVALID_START_DATE(73006),
		SIMULATION_INVALID_END_DATE(73007),
		SCENARIO_UNIQUE_CONSTRAINT_VOILATION(73008),
		PROJECT_TYPE_CANNOT_BE_BLANK(75000),
		PROJECT_ID_CANNOT_BE_BLANK(75001),
		SIM_PROCESS_DEF_ID_CANNOT_BE_BLANK(76000),
		PROCESS_DEF_ID_CANNOT_BE_BLANK(76001),
		PROCESS_NAME_CANNOT_BE_BLANK(76002),
		PROCESS_TYPE_CANNOT_BE_BLANK(76003),
		PROCESS_UNIQUE_CONSTRAINT_VOILATION(76008),
		IBPS_PROCESS_DOES_NOT_EXIST(348),
		PROCESS_DOES_NOT_EXIST(76004),
		CALENDAR_NOT_FOUND(78000),
		CALENDAR_ID_CANNOT_BE_BLANK(78001),
		CALENDAR_NAME_CANNOT_BE_BLANK(78002),
		CALENDAR_UNIQUE_CONSTRAINT_VOILATION(78008),
		CALENDAR_REFERENCIAL_CONSTRAINT_VOILATION(78009),
		INVALID_CALENDAR_RULE_DATE(78003),
		CABINET_NAME_CANNOT_BE_BLANK(79000),
		ROLE_ID_CANNOT_BE_BLANK(80000),
		ROLE_DOES_NOT_EXIST(80001),
		ROLE_NAME_CANNOT_BE_BLANK(80002),
		ROLE_UNIQUE_CONSTRAINT_VOILATION(80008),
		ROLE_REFERENCIAL_CONSTRAINT_VOILATION(80009),
		REPORT_NOT_FOUND(93000)
		;
		
		private int value;

		private WSExceptionConstant(int value) {
			this.value = value;
		}
		public int getValue(){
			return value;
		}
	}
	public static final String REQ_CONTENT_TYPE_JSON = "application/json";
	public static final String REQ_CONTENT_TYPE_XML = "text/xml";
	public static final String REQUEST_PARAM = "ws_request";
	public static final String WS_REQUEST_OBJECT = "WS_REQUEST_OBJECT";
	public static final String WS_RESPONSE = "WS_RESPONSE_XML";
	public static final String STATUS_SUCCESS = "SUCCESS";
	public static final String STATUS_EXCEPTION = "EXCEPTION";
	public static final String STATUS_TIMEOUT = "TIMEOUT";
	public static final String STATUS_Y = "Y";
	public static final String STATUS_N = "N";
	public static final int RESPONSE_OK = 0;
	public static final int RESPONSE_ERROR = 1;
	public static final String STATUS="Status";
	public static final String EMPTY_STRING="";
	public static final String CALENDAR_TYPE_IBPS = "I";
	public static final String CALENDAR_TYPE_SCENARIO = "S";
	public static final String SORT_ORDER_ASCENDING = "ASC";
	public static final String SORT_ORDER_DESCENDING = "DESC";

}
